### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by imbur** [imbur/thesis-template-latex#1]
- [X] valthiv --> varRef
- [X] handmade instance model
- [X] printer-compliant color selection
- [X] cblock --> cBlock
- [X] there are two blocks named b4 in the figure depicting the instance model
- [X] measurement environment
- [X] description of the patterns used for the measurements
- [X] port the rete network for the new theme
- [X] lookahead pattern matching for related work
- [x] plan --> search plan
- [x] generation --> calculation
- [x] I --> we
- [x] double check weights of lines; they should be thick enough to be visible
- [x] review pseudocode for flattening
- [x] write more details about search execution
- [x] local search debugger --> Local Search Debugger (capitalize)
- [x] pattern, graph pattern, query --> do not use query
- [x] add comments for appendix tables and figures as well
- [x] capitalize all component and phase names
- [x] appendix mapping for instance model names between the one opened in the editor and the hand drawn
- [x] abbreviations should be outside \emph{}
- [x] synchronize themes for workflow images
- [x] cost funcion and calculation should be more detailed
- [x] InstanceOf.operand --> Unary.operand in every places
- [x] add constraints for the arrows in SST, lengthen the arrows as well
